on:
  push:
    branches:
      - main
name: Deploy Test
jobs:
  test1:
    name: Deploy1
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

        

